spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/trader?verifyServerCertificate=false&useSSL=true
    username: root
    password: secret
server:
  port: 7070